### ISSUE TITLE
Failed to download video

### ISSUE THREAD

**Issue by kemiisto** [cykl/infoqscraper#23]
Running infoqscraper 0.1.1.dev0 on OS X 

    $ infoqscraper presentation download effective-api-design

results in

    Failed to create presentation effective-api-design.avi: Failed to download video at rtmpe://video.infoq.com/cfx/st/: rtmpdump exited with 2.

**Comment by cykl** [comment]
Thanks for the report. I'm able to reproduce it locally and I'm trying to troubleshoot it.

Basically, the server closes the connection after a while :

 ```
$ rtmpdump -e -V -r rtmpe://video.infoq.com/cfx/st/ -y flv:presentations/EffectiveJava_DesigningAnEffectiveAPI -o video.avi
[...]
DEBUG: (object begin)
DEBUG: Property: <Name:              level, STRING:	status>
DEBUG: Property: <Name:               code, STRING:	NetStream.Unpause.Notify>
DEBUG: Property: <Name:        description, STRING:	Unpausing presentations/EffectiveJava_DesigningAnEffectiveAPI.>
DEBUG: Property: <Name:            details, STRING:	presentations/EffectiveJava_DesigningAnEffectiveAPI>
DEBUG: Property: <Name:           clientid, STRING:	RTRg-Plb>
DEBUG: (object end)
DEBUG: (object end)
DEBUG: HandleInvoke, server invoking <onStatus>
DEBUG: HandleInvoke, onStatus: NetStream.Unpause.Notify
109112.864 kB / 3896.17 sec (93.8%)
DEBUG: RTMPSockBuf_Fill, recv returned -1. GetSockError(): 104 (Connection reset by peer)
Caught signal: 13, cleaning up, just a second...
ERROR: WriteN, RTMP send error 32 (42 bytes)
ERROR: RTMP_ReadPacket, failed to read RTMP packet body. len: 132
109144.432 kB / 3897.57 sec (93.8%)
DEBUG: RTMP_Read returned: 0
Download may be incomplete (downloaded about 93.80%), try resuming
DEBUG: Closing connection.
```

The stream does not seems to be corrupted since I can resume and complete the download using `-e`.

It does not seem specific to this stream since:

 - role-of-testing-in-agile-scott-ambler which is from 2007 and more than one hour long suffer from the same issue (stops after 117501.364 kB / 3792.33 sec (77.8%))
 - 15-apr-spreadsheets2.mp4 which is new and more than one hour long  also suffer from the issue (stops after 487582.744 kB / 4077.16 sec (83.0%))

I will sleep on it. Any help on troubleshooting is appreciated.

**Comment by cykl** [comment]
Could you give a try to the "automatically_resume_download_on_exit_2" branch ? It should solve the issue.

However, it seems that the SWF to png slide conversion does not work for this specific presentation. You get a black screen (you can use -t h264_overlay to see the speaker in the lower right corner). I will give it a look but can't promise it is fixable. I forgot the details but IIRC earliest infoq slides where rather difficult to extract.

**Comment by kemiisto** [comment]
I could confirm that downloading works on automatically_resume_download_on_exit_2 branch. Unfortunately, I also get a black screen. :(

**Comment by cykl** [comment]
Unfortunately there is nothing I can do to fix the black screen issue. It is a "bug" in swfrender and I don't have time to investigate it (AFAIK swftools are not actively maintained, but you could still try to fill an issue: we want to convert this [slide](http://cdn.infoq.com/statics_s1_20150916-0148/resource/presentations/effective-api-design/en/slides/slide8.swf) as png or jpg)

We could also try to use ffmpeg instead of swfrender to convert the slides. But IIRC it did not work or was not available in old fmmpeg releases (like on Debian stable). Few years have passed since, so perhaps the situation has improved ? 

Please open a dedicated ticket if it bother you. But it will not be on my top priority list, since it only affect some of the oldest presentations and any change would require lot of testing.
